pincritas=["Harry","Hermione","Ron","Neville","Draco"]
print(pincritas)
pincritas.append("Ana")
print(pincritas)
pincritas.extend(["Albus","Severus","Minerva","Hagrid"])
print(pincritas)
pincritas.insert(0, "Luna")
print(pincritas)
pincritas.pop()
print(pincritas)
pincritas.remove("Ana")
print(pincritas)
print(pincritas[0:3])